package com.jejakteknisi.app;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.view.*;import android.widget.*;import java.util.*;

public class MainActivity extends Activity{
 DatabaseHelper db; LinearLayout root,content; EditText search; Spinner grade; TextView count; boolean schematic=false;
 String[] grades={"Semua","A+++","A++ 2/32","A++ 16A","A++ 16B/A+","A+B","A+","A+ Samsung/A khusus","Pilihan 256","Pilihan 128","Pilihan 64","Pilihan 32","Pilihan 16","Pilihan 8GB"};
 public void onCreate(Bundle b){super.onCreate(b);db=new DatabaseHelper(this);showMain();}
 TextView tv(String s,int size){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(Color.DKGRAY);t.setPadding(24,16,24,16);return t;}
 Button btn(String s){Button b=new Button(this);b.setText(s);return b;}
 void showMain(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.rgb(245,247,250));
  TextView h=tv("JEJAK TEKNISI",22);h.setTextColor(Color.rgb(21,101,192));h.setGravity(Gravity.CENTER);root.addView(h,new LinearLayout.LayoutParams(-1,70));
  LinearLayout nav=new LinearLayout(this);Button e=btn("Grade eMMC");Button sc=btn("Schematic");nav.addView(e,new LinearLayout.LayoutParams(0,-2,1));nav.addView(sc,new LinearLayout.LayoutParams(0,-2,1));root.addView(nav);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);root.addView(content,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);
  e.setOnClickListener(v->{schematic=false;render();});sc.setOnClickListener(v->{schematic=true;render();});render(); }
 void render(){content.removeAllViews();search=new EditText(this);search.setHint(schematic?"Cari model / judul schematic":"Cari kode eMMC / grade / kapasitas");content.addView(search);if(!schematic){grade=new Spinner(this);grade.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,grades));content.addView(grade);LinearLayout actions=new LinearLayout(this);Button scan=btn("📷 Scan OCR");Button add=btn("＋ Tambah");actions.addView(scan,new LinearLayout.LayoutParams(0,-2,1));actions.addView(add,new LinearLayout.LayoutParams(0,-2,1));content.addView(actions);scan.setOnClickListener(v->startActivity(new Intent(this,ScannerActivity.class)));add.setOnClickListener(v->addDialog());grade.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onNothingSelected(android.widget.AdapterView<?> p){}public void onItemSelected(android.widget.AdapterView<?> p,View v,int pos,long id){loadEmmc();}});search.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int d){}public void onTextChanged(CharSequence s,int a,int b,int c){loadEmmc();}public void afterTextChanged(android.text.Editable e){}});loadEmmc();}else{Button add=btn("＋ Tambah Schematic");content.addView(add);add.setOnClickListener(v->schematicDialog());search.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int b,int c){}public void onTextChanged(CharSequence s,int a,int b,int c){loadSchematic();}public void afterTextChanged(android.text.Editable e){}});loadSchematic();}}
 void loadEmmc(){content.removeViews(3,content.getChildCount()-3);String g=grade==null?"Semua":grade.getSelectedItem().toString();List<String[]> rows=db.search(search==null?"":search.getText().toString(),g);count=tv("Hasil: "+rows.size(),14);content.addView(count);for(String[] r:rows){TextView t=tv(r[0]+"\n"+r[1]+"  •  "+r[2]+"\n"+r[3],16);t.setBackgroundColor(Color.WHITE);t.setOnClickListener(v->detail(r));content.addView(t);}}
 void loadSchematic(){content.removeViews(2,content.getChildCount()-2);List<String[]> rows=db.schematics(search==null?"":search.getText().toString());content.addView(tv("Schematic: "+rows.size(),14));for(String[] r:rows){TextView t=tv("📐 "+r[0]+"\n"+r[1]+"\n"+r[3],17);t.setBackgroundColor(Color.WHITE);t.setOnClickListener(v->schematicDetail(r));content.addView(t);}}
 void detail(String[] r){new AlertDialog.Builder(this).setTitle(r[0]).setMessage("Grade: "+r[1]+"\nKapasitas: "+r[2]+"\n\n"+r[3]).setPositiveButton("Tutup",null).setNegativeButton("Hapus",(d,w)->{db.deleteEmmc(r[0]);loadEmmc();}).show();}
 void addDialog(){LinearLayout l=new LinearLayout(this);l.setPadding(30,0,30,0);l.setOrientation(LinearLayout.VERTICAL);EditText a=new EditText(this);a.setHint("Kode EMMC");EditText b=new EditText(this);b.setHint("Grade");EditText c=new EditText(this);c.setHint("Kapasitas");EditText d=new EditText(this);d.setHint("Catatan");for(EditText x:new EditText[]{a,b,c,d})l.addView(x);new AlertDialog.Builder(this).setTitle("Tambah EMMC").setView(l).setPositiveButton("Simpan",(x,w)->{db.addEmmc(a.getText().toString(),b.getText().toString(),c.getText().toString(),d.getText().toString());loadEmmc();}).setNegativeButton("Batal",null).show();}
 void schematicDialog(){LinearLayout l=new LinearLayout(this);l.setPadding(30,0,30,0);l.setOrientation(LinearLayout.VERTICAL);EditText a=new EditText(this);a.setHint("Model HP");EditText b=new EditText(this);b.setHint("Judul schematic");l.addView(a);l.addView(b);new AlertDialog.Builder(this).setTitle("Tambah Schematic").setView(l).setMessage("Versi awal menyimpan model/judul. Gambar schematic dapat ditambahkan ke res/drawable pada tahap berikutnya.").setPositiveButton("Simpan",null).setNegativeButton("Batal",null).show();}
 void schematicDetail(String[] r){new AlertDialog.Builder(this).setTitle(r[0]).setMessage(r[1]+"\n\n"+r[3]).setPositiveButton("Buka",(d,w)->{}).setNegativeButton("Tutup",null).show();}
}
