package com.jejakteknisi.app;

import android.Manifest;import android.app.*;import android.os.*;import android.content.pm.PackageManager;import android.graphics.*;import android.view.*;import android.widget.*;import androidx.annotation.NonNull;import androidx.camera.core.*;import androidx.camera.lifecycle.ProcessCameraProvider;import androidx.camera.view.PreviewView;import androidx.core.app.ActivityCompat;import androidx.core.content.ContextCompat;import com.google.common.util.concurrent.ListenableFuture;import com.google.mlkit.vision.common.InputImage;import com.google.mlkit.vision.text.TextRecognition;import com.google.mlkit.vision.text.latin.TextRecognizerOptions;

public class ScannerActivity extends Activity{
 PreviewView preview; ImageCapture capture; TextView result;
 public void onCreate(Bundle b){super.onCreate(b);LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);preview=new PreviewView(this);l.addView(preview,new LinearLayout.LayoutParams(-1,0,1));Button scan=new Button(this);scan.setText("SCAN KODE EMMC");l.addView(scan);result=new TextView(this);result.setPadding(20,20,20,20);l.addView(result);setContentView(l);scan.setOnClickListener(v->take());if(ContextCompat.checkSelfPermission(this,Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED)ActivityCompat.requestPermissions(this,new String[]{Manifest.permission.CAMERA},7);else start();}
 void start(){ListenableFuture<ProcessCameraProvider> f=ProcessCameraProvider.getInstance(this);f.addListener(()->{try{ProcessCameraProvider p=f.get();Preview pr=new Preview.Builder().build();pr.setSurfaceProvider(preview.getSurfaceProvider());capture=new ImageCapture.Builder().setTargetRotation(preview.getDisplay().getRotation()).build();p.unbindAll();p.bindToLifecycle(this,CameraSelector.DEFAULT_BACK_CAMERA,pr,capture);}catch(Exception e){result.setText(e.toString());}},ContextCompat.getMainExecutor(this));}
 void take(){if(capture==null)return;capture.takePicture(ContextCompat.getMainExecutor(this),new ImageCapture.OnImageCapturedCallback(){public void onCaptureSuccess(@NonNull ImageProxy ip){Bitmap b=preview.getBitmap();ip.close();if(b==null){result.setText("Gagal mengambil gambar");return;}InputImage im=InputImage.fromBitmap(b,0);TextRecognition.getClient(TextRecognizerOptions.DEFAULT_OPTIONS).process(im).addOnSuccessListener(t->result.setText("Hasil OCR:\n"+t.getText())).addOnFailureListener(e->result.setText("OCR gagal: "+e.getMessage()));}public void onError(@NonNull ImageCaptureException e){result.setText("Kamera: "+e.getMessage());}});}
 public void onRequestPermissionsResult(int r,@NonNull String[] p,@NonNull int[] g){super.onRequestPermissionsResult(r,p,g);if(r==7&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED)start();}
}
