package com.jejakteknisi.gradeemmc;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.graphics.drawable.GradientDrawable;import android.speech.RecognizerIntent;import android.view.*;import android.widget.*;import java.util.*;

public class MainActivity extends Activity{
    static final int VOICE=71; int dp(float v){return (int)(v*getResources().getDisplayMetrics().density+.5f);}
    @Override public void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_main);
        findViewById(R.id.btnScan).setOnClickListener(v->startActivity(new Intent(this,ScannerActivity.class)));
        findViewById(R.id.btnVoice).setOnClickListener(v->voice());findViewById(R.id.btnDatabase).setOnClickListener(v->showDb());findViewById(R.id.btnAdd).setOnClickListener(v->edit(null));findViewById(R.id.btnSettings).setOnClickListener(v->settings());
    }
    void voice(){try{Intent i=new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE,"id-ID");i.putExtra(RecognizerIntent.EXTRA_PROMPT,"Sebutkan kode eMMC");startActivityForResult(i,VOICE);}catch(Exception e){Toast.makeText(this,"Voice tidak tersedia di perangkat ini",Toast.LENGTH_SHORT).show();}}
    @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==VOICE&&c==RESULT_OK&&d!=null){ArrayList<String>x=d.getStringArrayListExtra(RecognizerIntent.EXTRA_RESULTS);if(x!=null&&!x.isEmpty())showResult(x.get(0));}}
    void showResult(String q){EmmcRecord e=DatabaseStore.find(this,q);if(e!=null)showCard(e);else{ArrayList<EmmcRecord>s=DatabaseStore.similar(this,q);StringBuilder m=new StringBuilder("Hasil suara: ").append(q).append("\n\n");if(s.isEmpty())m.append("Belum ada kecocokan database.");else{m.append("Kandidat terdekat:\n");for(EmmcRecord z:s)m.append("• ").append(z.code).append(" — ").append(z.capacity).append(" — Grade ").append(z.grade).append("\n");}new AlertDialog.Builder(this).setTitle("Kode tidak ditemukan").setMessage(m.toString()).setPositiveButton("CARI WEB",(di,w)->web(q)).setNegativeButton("OK",null).show();}}
    void web(String q){startActivity(new Intent(Intent.ACTION_VIEW,android.net.Uri.parse("https://www.google.com/search?q="+android.net.Uri.encode(q+" eMMC datasheet"))));}
    void showCard(EmmcRecord e){String msg="Kode : "+e.code+"\nManufacturer : "+e.manufacturer+"\nKapasitas : "+e.capacity+"\neMMC Version : "+e.version+"\n\nGRADE eMMC : "+(e.grade.isEmpty()?"Belum ditentukan":e.grade)+"\nPackage : "+e.pack+"\nSumber : "+e.source;new AlertDialog.Builder(this).setTitle("eMMC Ditemukan").setMessage(msg).setPositiveButton("EDIT",(d,w)->edit(e)).setNeutralButton("CARI",(d,w)->web(e.code)).setNegativeButton("TUTUP",null).show();}
    void showDb(){ArrayList<EmmcRecord>a=DatabaseStore.load(this);StringBuilder b=new StringBuilder();for(EmmcRecord e:a)b.append(e.code).append("\n").append(e.manufacturer).append(" • ").append(e.capacity).append(" • Grade: ").append(e.grade).append("\n\n");new AlertDialog.Builder(this).setTitle("Database eMMC • "+a.size()+" data").setMessage(b.toString()).setPositiveButton("TAMBAH",(d,w)->edit(null)).setNegativeButton("TUTUP",null).show();}
    void edit(EmmcRecord old){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(10),0,dp(10),0);EditText[]x=new EditText[7];String[]h={"Kode eMMC","Manufacturer","Kapasitas","eMMC Version","Grade eMMC","Package","Sumber"};String[]val=old==null?new String[7]:new String[]{old.code,old.manufacturer,old.capacity,old.version,old.grade,old.pack,old.source};for(int i=0;i<7;i++){x[i]=new EditText(this);x[i].setHint(h[i]);x[i].setText(val[i]==null?"":val[i]);box.addView(x[i]);}new AlertDialog.Builder(this).setTitle(old==null?"Tambah Data eMMC":"Edit Data eMMC").setView(box).setNegativeButton("BATAL",null).setPositiveButton("SIMPAN",(d,w)->{String code=x[0].getText().toString().trim();if(code.isEmpty()){Toast.makeText(this,"Kode eMMC wajib diisi",Toast.LENGTH_SHORT).show();return;}ArrayList<EmmcRecord>a=DatabaseStore.load(this);EmmcRecord n=new EmmcRecord(code,x[1].getText().toString().trim(),x[2].getText().toString().trim(),x[3].getText().toString().trim(),x[4].getText().toString().trim(),x[5].getText().toString().trim(),x[6].getText().toString().trim());boolean done=false;for(int i=0;i<a.size();i++)if(a.get(i).code.equalsIgnoreCase(n.code)){a.set(i,n);done=true;break;}if(!done)a.add(n);DatabaseStore.save(this,a);Toast.makeText(this,"Data eMMC & Grade disimpan",Toast.LENGTH_SHORT).show();}).show();}
    void settings(){new AlertDialog.Builder(this).setTitle("Pengaturan Jejak Teknisi").setItems(new String[]{"Foto dulu, baru OCR","Enhance gambar sebelum OCR","Grade eMMC tetap aktif","Jika tidak ada, cari di web","Voice search aktif"},null).setPositiveButton("OK",null).show();}
}
